<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Override;
use App\Enums\PrCategory;
use App\Enums\Rarity;
use App\Services\AI\AnalysisStatus;
use App\Services\AI\AnalysisType;
use Illuminate\Console\Command;

/**
 * Generates TypeScript string-literal unions from the backed PHP enums the
 * frontend mirrors, so the two can't drift. The page-prop *shapes* stay
 * hand-written in resources/js/types (controllers return inline arrays, not
 * typed DTOs); this covers the enum surface, which is what actually drifts.
 */
final class GenerateTypeScriptEnumsCommand extends Command
{
    #[Override]
    protected $signature = 'typescript:enums {--check : Fail if the generated file is stale instead of rewriting it} {--path= : Override the output path (for tests only)}';

    #[Override]
    protected $description = 'Generate TypeScript unions from backed PHP enums into resources/js/types/generated.ts';

    /**
     * @var list<class-string>
     */
    private const array ENUMS = [
        Rarity::class,
        PrCategory::class,
        AnalysisStatus::class,
        AnalysisType::class,
    ];

    public function handle(): int
    {
        $expected = $this->build();
        $path = $this->option('path') ?? resource_path('js/types/generated.ts');

        if ($this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';
            if ($current !== $expected) {
                $this->error('resources/js/types/generated.ts is stale. Run `php artisan typescript:enums`.');

                return self::FAILURE;
            }
            $this->info('TypeScript enums are up to date.');

            return self::SUCCESS;
        }

        file_put_contents($path, $expected);
        $this->info('Wrote '.$path);

        return self::SUCCESS;
    }

    private function build(): string
    {
        $blocks = [];
        foreach (self::ENUMS as $enum) {
            $name = class_basename($enum);
            /** @var list<string> $values */
            $values = array_map(static fn ($case): string => (string) $case->value, $enum::cases());
            $union = implode(' | ', array_map(static fn (string $v): string => "'{$v}'", $values));
            $array = implode(', ', array_map(static fn (string $v): string => "'{$v}'", $values));

            $blocks[] = "export type {$name} = {$union};\n"
                ."export const ".self::constName($name)." = [{$array}] as const;";
        }

        return "// AUTO-GENERATED by `php artisan typescript:enums`. Do not edit by hand.\n"
            ."// Regenerate after changing any backed PHP enum; CI fails if stale.\n\n"
            .implode("\n\n", $blocks)."\n";
    }

    private static function constName(string $typeName): string
    {
        return mb_strtoupper((string) preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', $typeName)).'_VALUES';
    }
}
