<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use App\Enums\Effort;
use App\Enums\ExperienceLevel;
use App\Enums\FeedbackReason;
use App\Enums\FeedbackSubject;
use App\Enums\GoalType;
use App\Enums\Mood;
use App\Enums\NotificationKind;
use App\Enums\PerformanceEvidenceKind;
use App\Enums\PlannedSessionStatus;
use App\Enums\PrCategory;
use App\Enums\Rarity;
use App\Services\AI\Anchor\AnchorKind;
use App\Services\AI\AnalysisStatus;
use App\Services\AI\AnalysisType;
use App\Http\Controllers\InboxController;
use App\Models\AI\RunQuestion;
use App\Models\Feedback;
use App\Models\RaceGoal;
use App\Services\Run\FeedFilters;
use App\Services\Run\Metrics\DecouplingBands;
use App\Services\Weather\WeatherSnapshot;
use Illuminate\Console\Command;

/**
 * Generates TypeScript string-literal unions from the backed PHP enums the
 * frontend mirrors, plus the scalar constants it mirrors, so the two can't drift. The page-prop *shapes* stay
 * hand-written in resources/js/types (controllers return inline arrays, not
 * typed DTOs); this covers the enum surface, which is what actually drifts.
 */
#[Description('Generate TypeScript unions from backed PHP enums, and the scalar constants the frontend mirrors, into resources/js/types/generated.ts')]
#[Signature('typescript:enums {--check : Fail if the generated file is stale instead of rewriting it} {--path= : Override the output path (for tests only)}')]
final class GenerateTypeScriptEnumsCommand extends Command
{
    /**
     * @var list<class-string>
     */
    private const array ENUMS = [
        Rarity::class,
        Effort::class,
        PrCategory::class,
        AnalysisStatus::class,
        AnalysisType::class,
        NotificationKind::class,
        PlannedSessionStatus::class,
        ExperienceLevel::class,
        GoalType::class,
        FeedbackSubject::class,
        FeedbackReason::class,
        AnchorKind::class,
        PerformanceEvidenceKind::class,
        Mood::class,
    ];

    /**
     * @var array<string, int|float>
     */
    private const array SCALARS = [
        'HOT_RUN_TEMP_C' => WeatherSnapshot::HOT_RUN_TEMP_C,
        'INBOX_PER_PAGE' => InboxController::PER_PAGE,
        'FEED_WEEKS_PER_PAGE' => FeedFilters::WEEKS_PER_PAGE,
        'MIN_QUESTION_LENGTH' => RunQuestion::MIN_QUESTION_LENGTH,
        'MAX_QUESTION_LENGTH' => RunQuestion::MAX_QUESTION_LENGTH,
        'MAX_FEEDBACK_NOTE_LENGTH' => Feedback::MAX_NOTE_LENGTH,
        'DECOUPLING_HIGH_PCT' => DecouplingBands::HIGH,
        'MIN_GOAL_TIME_SEC' => RaceGoal::MIN_GOAL_TIME_SEC,
        'MAX_GOAL_TIME_SEC' => RaceGoal::MAX_GOAL_TIME_SEC,
    ];

    public function handle(): int
    {
        $expected = $this->build();
        $path = $this->option('path') ?? resource_path('js/types/generated.ts');

        if ($this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';
            if ($current !== $expected) {
                $this->error('resources/js/types/generated.ts is stale. Run `php artisan typescript:enums`.');

                return self::FAILURE;
            }
            $this->info('TypeScript enums are up to date.');

            return self::SUCCESS;
        }

        file_put_contents($path, $expected);
        $this->info('Wrote '.$path);

        return self::SUCCESS;
    }

    private function build(): string
    {
        $blocks = [];
        foreach (self::ENUMS as $enum) {
            $name = class_basename($enum);
            /** @var list<string> $values */
            $values = array_map(static fn ($case): string => (string) $case->value, $enum::cases());
            $union = implode(' | ', array_map(static fn (string $v): string => "'{$v}'", $values));
            $array = implode(', ', array_map(static fn (string $v): string => "'{$v}'", $values));

            $blocks[] = "export type {$name} = {$union};\n"
                ."export const ".self::constName($name)." = [{$array}] as const;";
        }

        $scalars = [];
        foreach (self::SCALARS as $name => $value) {
            $scalars[] = "export const {$name} = ".(string) $value.';';
        }
        $blocks[] = implode("\n", $scalars);

        return "// AUTO-GENERATED by `php artisan typescript:enums`. Do not edit by hand.\n"
            ."// Regenerate after changing any backed PHP enum or mirrored constant; CI fails if stale.\n\n"
            .implode("\n\n", $blocks)."\n";
    }

    private static function constName(string $typeName): string
    {
        return mb_strtoupper((string) preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', $typeName)).'_VALUES';
    }
}
