import { memo, useId, type CSSProperties } from 'react';

import { cn } from '@/lib/cn';

/** The ten drawn faces of the character, as generated by resources/brand/build-mascot.mjs. */
export type TemariExpression =
    | 'resting'
    | 'pleased'
    | 'impressed'
    | 'hyped'
    | 'skeptical'
    | 'unimpressed'
    | 'challenging'
    | 'concerned'
    | 'disappointed'
    | 'celebrating';

export const TEMARI_EXPRESSIONS: readonly TemariExpression[] = [
    'resting',
    'pleased',
    'impressed',
    'hyped',
    'skeptical',
    'unimpressed',
    'challenging',
    'concerned',
    'disappointed',
    'celebrating',
];

export type TemariPose =
    | 'proud'
    | 'pumped'
    | 'excited'
    | 'holding'
    | 'reading'
    | 'wobble'
    | 'observational'
    | 'glow'
    | TemariExpression;

export interface TemariEquipped {
    headband?: 'uncommon' | 'rare' | 'epic' | 'legendary' | null;
    medal?: 'first' | 'gold' | 'silver' | 'platinum' | 'none';
    shirt?: 'beginner' | 'earlyBird' | 'rainWarrior' | 'legendary' | null;
    shorts?: 'lightweight' | 'explorer' | 'negativeSplit' | 'marathon' | null;
    shoes?: 'basic' | 'speed' | 'rugged' | 'legendary' | null;
    aura?:
        | 'warmup'
        | 'heatwave'
        | 'calm'
        | 'champion'
        | 'windrunner'
        | true
        | null;
}

/**
 * Discrete season-arc coverage states for the Plan tab's season summary —
 * the only render site that passes this prop. `deload` is intentionally not
 * a variant here: the caller resolves a deload week to the last non-deload
 * phase before rendering, so accretion pauses instead of resetting.
 */
export type SeasonPhase = 'base' | 'build' | 'peak' | 'taper';

export interface TemariProtoProps {
    pose?: TemariPose;
    size?: number;
    /** Cream-bg vs sky-bg surface — picks the silhouette outline that stays visible. */
    tone?: 'cream' | 'sky';
    equipped?: TemariEquipped | null;
    /** `true` = pose-driven animation, `false` = static, string = explicit CSS animation. */
    animate?: boolean | string;
    /**
     * Soft SVG drop shadow under the character. Default `true`. Set `false` when
     * the mascot sits inside a 3D-transformed ancestor (e.g. the `.kartu-tilt`
     * card corner) — Chromium won't rasterise an SVG filter under `perspective()`,
     * which makes the whole filtered group vanish.
     */
    dropShadow?: boolean;
    /**
     * Season thread-coverage overlay — only the Plan tab's season summary
     * passes this. Everywhere else the ball keeps its constant default
     * texture, so the mascot never becomes phase-aware app-wide.
     */
    seasonPhase?: SeasonPhase;
    className?: string;
}

// ── Character geometry (mirrors resources/brand/build-mascot.mjs) ────

const CX = 50;
const CY = 52;
const BODY_R = 31;
const HALO_R = 41;
const AURA_R = 47;
const CLIP_R = BODY_R - 2.2;
const EYE_Y = 50;
const EYE_S = 10;
const EYE_L = CX - EYE_S;
const EYE_R = CX + EYE_S;

const SKY = '#241c54';
const CREAM = '#f5f0e4';
const GOLD_INK = '#896826';
const INK = '#1a1812';
const LACE = '#b23a4f';

/**
 * Mood halo, one entry per drawn state. Values are the mood/line/stone tokens
 * already darkened to clear 3:1 on cream — the ring is structural, so a token
 * that fails bare is not usable raw. TemariProto.test.tsx recomputes them from
 * build-tokens.mjs, so a token move fails the suite instead of drifting.
 */
const HALO: Record<string, { color: string; width: number }> = {
    neutral: { color: '#908a79', width: 6 },
    easy: { color: '#2f8f63', width: 6 },
    blazing: { color: '#af841b', width: 8 },
    gold: { color: '#ae8430', width: 9 },
    chill: { color: '#55488f', width: 6 },
    stone: { color: '#938a78', width: 5 },
    wobbly: { color: '#b23a4f', width: 7 },
    gassed: { color: '#7a2030', width: 6 },
};

type EyeShape = 'open' | 'wide' | 'lid' | 'wink-r';

type MouthShape =
    | 'smile-sm'
    | 'smile-md'
    | 'flat'
    | 'wry'
    | 'smirk'
    | 'frown-sm'
    | 'frown-md'
    | 'o'
    | 'open';

interface ExpressionSpec {
    /** Brow endpoints as offsets from the eye line: [outer, inner]. Negative is above. */
    brow: [number, number];
    browR?: [number, number];
    eyes: EyeShape;
    mouth: MouthShape;
    halo: string;
}

const EXPRESSION_SPEC: Record<TemariExpression, ExpressionSpec> = {
    resting: {
        brow: [-10, -11],
        eyes: 'open',
        mouth: 'smile-sm',
        halo: 'neutral',
    },
    pleased: {
        brow: [-11, -12.5],
        eyes: 'open',
        mouth: 'smile-md',
        halo: 'easy',
    },
    impressed: { brow: [-14, -15.5], eyes: 'wide', mouth: 'o', halo: 'easy' },
    hyped: { brow: [-15, -16], eyes: 'wide', mouth: 'open', halo: 'blazing' },
    skeptical: {
        brow: [-15.5, -12],
        browR: [-9, -9],
        eyes: 'wink-r',
        mouth: 'wry',
        halo: 'chill',
    },
    unimpressed: {
        brow: [-9, -9],
        eyes: 'lid',
        mouth: 'flat',
        halo: 'stone',
    },
    challenging: {
        brow: [-13.5, -8.5],
        eyes: 'open',
        mouth: 'smirk',
        halo: 'gold',
    },
    concerned: {
        brow: [-9.5, -13.5],
        eyes: 'open',
        mouth: 'frown-sm',
        halo: 'wobbly',
    },
    disappointed: {
        brow: [-9, -12],
        eyes: 'lid',
        mouth: 'frown-md',
        halo: 'gassed',
    },
    celebrating: {
        brow: [-13, -14.5],
        eyes: 'wide',
        mouth: 'open',
        halo: 'gold',
    },
};

/**
 * The eight poses that predate the ten drawn faces keep their names so every
 * call site and both maps in lib/temariPose.ts stay untouched; each resolves
 * to the face that carries the same read.
 */
const POSE_TO_EXPRESSION: Record<TemariPose, TemariExpression> = {
    proud: 'pleased',
    pumped: 'hyped',
    excited: 'impressed',
    holding: 'resting',
    reading: 'resting',
    wobble: 'concerned',
    observational: 'resting',
    glow: 'celebrating',
    resting: 'resting',
    pleased: 'pleased',
    impressed: 'impressed',
    hyped: 'hyped',
    skeptical: 'skeptical',
    unimpressed: 'unimpressed',
    challenging: 'challenging',
    concerned: 'concerned',
    disappointed: 'disappointed',
    celebrating: 'celebrating',
};

const POSE_ANIM: Record<TemariPose, string> = {
    proud: 'temari-bob 4s ease-in-out infinite',
    pumped: 'temari-bounce 1.4s ease-in-out infinite',
    excited: 'temari-bounce 0.9s ease-in-out infinite',
    holding: 'temari-bob 4s ease-in-out infinite',
    reading: 'temari-tilt 3.5s ease-in-out infinite',
    wobble: 'temari-sway 2.4s ease-in-out infinite',
    observational: 'temari-nod 3.6s ease-in-out infinite',
    glow: 'temari-bob 3.2s ease-in-out infinite, temari-breathe 3.2s ease-in-out infinite',
    resting: 'temari-bob 4s ease-in-out infinite',
    pleased: 'temari-bob 3.6s ease-in-out infinite',
    impressed: 'temari-nod 3s ease-in-out infinite',
    hyped: 'temari-bounce 1.2s ease-in-out infinite',
    skeptical: 'temari-tilt 4s ease-in-out infinite',
    unimpressed: 'temari-nod 5s ease-in-out infinite',
    challenging: 'temari-tilt 3s ease-in-out infinite',
    concerned: 'temari-sway 2.8s ease-in-out infinite',
    disappointed: 'temari-sway 4.4s ease-in-out infinite',
    celebrating:
        'temari-bounce 1s ease-in-out infinite, temari-breathe 3.2s ease-in-out infinite',
};

// ── Placement ────────────────────────────────────────────────────────
// The viewBox is the one every call site already reserves space for, and the
// character is drawn in its own 100-unit space, so it is scaled and centred
// into that box. Both derive from BOUNDS as the generator exports it: the
// widest thing on a bare character is the mood halo, but an equipped aura
// reaches further on every side, and reading only the halo is what clipped
// the top edge before.

const VIEW_W = 120;
const VIEW_H = 140;
const VIEW_Y = -4;

const BOUNDS = {
    top: 6.5,
    bottom: 97.5,
    left: 4.5,
    right: 95.5,
    withAccessories: { bottom: 92, outer: 48.2 },
};

const EXTENT = {
    left: Math.min(BOUNDS.left, CX - BOUNDS.withAccessories.outer),
    right: Math.max(BOUNDS.right, CX + BOUNDS.withAccessories.outer),
    top: Math.min(BOUNDS.top, CY - BOUNDS.withAccessories.outer),
    bottom: Math.max(
        BOUNDS.bottom,
        BOUNDS.withAccessories.bottom,
        CY + BOUNDS.withAccessories.outer,
    ),
};

const PLACE_SCALE = Math.min(
    VIEW_W / (EXTENT.right - EXTENT.left),
    VIEW_H / (EXTENT.bottom - EXTENT.top),
);

const PLACE_TRANSFORM = [
    `translate(${(VIEW_W / 2 - ((EXTENT.left + EXTENT.right) / 2) * PLACE_SCALE).toFixed(3)}`,
    `${(VIEW_Y + VIEW_H / 2 - ((EXTENT.top + EXTENT.bottom) / 2) * PLACE_SCALE).toFixed(3)})`,
    `scale(${PLACE_SCALE.toFixed(4)})`,
].join(' ');

// ── Accessory catalogue ──────────────────────────────────────────────
// Colour carries rarity and a small detail carries the theme, straight from
// resources/brand/build-accessories.mjs. The values were swept for same-slot
// separation, so TemariProto.test.tsx pins them against that generator.

type DetailKind =
    | 'sunrise'
    | 'rain'
    | 'splitPanel'
    | 'speedStripe'
    | 'lugs'
    | 'crownStud'
    | 'medalStar'
    | 'medalRing';

interface ItemSpec {
    color: string;
    detail?: DetailKind;
}

const HEADBAND_ITEMS: Record<string, ItemSpec> = {
    uncommon: { color: '#2fb350' },
    rare: { color: '#2f81f7' },
    epic: { color: '#a855f7', detail: 'crownStud' },
    legendary: { color: '#f5a623', detail: 'crownStud' },
};

const MEDAL_ITEMS: Record<string, ItemSpec> = {
    first: { color: '#a98f6b' },
    silver: { color: '#b9c0c9', detail: 'medalStar' },
    gold: { color: '#d9a53c', detail: 'medalStar' },
    platinum: { color: '#dfe6f2', detail: 'medalRing' },
};

const SHIRT_ITEMS: Record<string, ItemSpec> = {
    beginner: { color: '#a99f8a' },
    earlyBird: { color: '#2f8f63', detail: 'sunrise' },
    rainWarrior: { color: '#2f81f7', detail: 'rain' },
    legendary: { color: '#f5a623' },
};

const SHORTS_ITEMS: Record<string, ItemSpec> = {
    lightweight: { color: '#a99f8a' },
    explorer: { color: '#256f4d' },
    negativeSplit: { color: '#2f81f7', detail: 'splitPanel' },
    marathon: { color: '#a855f7' },
};

const SHOES_ITEMS: Record<string, ItemSpec> = {
    basic: { color: '#a99f8a' },
    speed: { color: '#b23a4f', detail: 'speedStripe' },
    rugged: { color: '#256f4d', detail: 'lugs' },
    legendary: { color: '#f5a623', detail: 'speedStripe' },
};

const AURA_ITEMS: Record<string, { color: string; dash: string }> = {
    warmup: { color: '#d9a53c', dash: '1.5 7' },
    heatwave: { color: '#8d2c3d', dash: '3 5' },
    calm: { color: '#55488f', dash: '0.1 6' },
    champion: { color: '#a855f7', dash: '999' },
    windrunner: { color: '#2f81f7', dash: '14 6' },
};

// ── Season coverage (Plan tab season summary only) ───────────────────

interface SeasonCoverageConfig {
    angles: number[];
    width: number;
    opacity: number;
    shine?: boolean;
}

const FULL_COVERAGE = {
    angles: [-30, -10, 15, 40, 65, 85],
    width: 3,
    opacity: 0.85,
};

const SEASON_COVERAGE: Record<SeasonPhase, SeasonCoverageConfig> = {
    base: { angles: [20], width: 1.4, opacity: 0.3 },
    build: { angles: [-15, 25, 60], width: 2.2, opacity: 0.55 },
    peak: FULL_COVERAGE,
    taper: { ...FULL_COVERAGE, shine: true },
};

const SEASON_COLORS = ['#8d2c3d', '#d9a53c', '#362a73', '#256f4d', '#6b3fa0'];

// ── Primitives ───────────────────────────────────────────────────────

function Stroke({
    d,
    width = 3.8,
    color = SKY,
}: Readonly<{ d: string; width?: number; color?: string }>) {
    return (
        <path
            d={d}
            fill="none"
            stroke={color}
            strokeWidth={width}
            strokeLinecap="round"
        />
    );
}

function Band({
    y,
    height,
    fill,
}: Readonly<{ y: number; height: number; fill: string }>) {
    return (
        <rect
            x={CX - BODY_R}
            y={y}
            width={BODY_R * 2}
            height={height}
            fill={fill}
        />
    );
}

function Brow({
    x,
    outerY,
    innerY,
    side,
}: Readonly<{ x: number; outerY: number; innerY: number; side: 'l' | 'r' }>) {
    const outerX = side === 'l' ? x - 5.5 : x + 5.5;
    const innerX = side === 'l' ? x + 5.5 : x - 5.5;
    return (
        <Stroke
            d={`M${outerX} ${(EYE_Y + outerY).toFixed(1)} L${innerX} ${(EYE_Y + innerY).toFixed(1)}`}
        />
    );
}

function OpenEye({ x, r }: Readonly<{ x: number; r: number }>) {
    return <circle cx={x} cy={EYE_Y} r={r} fill={SKY} />;
}

function LidEye({ x }: Readonly<{ x: number }>) {
    return <Stroke d={`M${x - 4.2} ${EYE_Y} H${x + 4.2}`} width={4.4} />;
}

function Eyes({ shape }: Readonly<{ shape: EyeShape }>) {
    if (shape === 'wide') {
        return (
            <>
                <OpenEye x={EYE_L} r={5.3} />
                <OpenEye x={EYE_R} r={5.3} />
            </>
        );
    }
    if (shape === 'lid') {
        return (
            <>
                <LidEye x={EYE_L} />
                <LidEye x={EYE_R} />
            </>
        );
    }
    if (shape === 'wink-r') {
        return (
            <>
                <OpenEye x={EYE_L} r={4.4} />
                <LidEye x={EYE_R} />
            </>
        );
    }
    return (
        <>
            <OpenEye x={EYE_L} r={4.4} />
            <OpenEye x={EYE_R} r={4.4} />
        </>
    );
}

function Mouth({ shape }: Readonly<{ shape: MouthShape }>) {
    switch (shape) {
        case 'smile-md':
            return (
                <Stroke
                    d={`M${CX - 8} ${EYE_Y + 12.5} Q${CX} ${EYE_Y + 19} ${CX + 8} ${EYE_Y + 12.5}`}
                />
            );
        case 'flat':
            return <Stroke d={`M${CX - 6.5} ${EYE_Y + 13.5} H${CX + 6.5}`} />;
        case 'wry':
            return (
                <Stroke
                    d={`M${CX - 6} ${EYE_Y + 14} Q${CX + 1} ${EYE_Y + 11.5} ${CX + 7} ${EYE_Y + 13.5}`}
                />
            );
        case 'smirk':
            return (
                <Stroke
                    d={`M${CX - 6} ${EYE_Y + 14} Q${CX + 2} ${EYE_Y + 17.5} ${CX + 8} ${EYE_Y + 11.5}`}
                />
            );
        case 'frown-sm':
            return (
                <Stroke
                    d={`M${CX - 6.5} ${EYE_Y + 15.5} Q${CX} ${EYE_Y + 11.5} ${CX + 6.5} ${EYE_Y + 15.5}`}
                />
            );
        case 'frown-md':
            return (
                <Stroke
                    d={`M${CX - 7.5} ${EYE_Y + 16.5} Q${CX} ${EYE_Y + 10.5} ${CX + 7.5} ${EYE_Y + 16.5}`}
                />
            );
        case 'o':
            return (
                <ellipse
                    cx={CX}
                    cy={EYE_Y + 12.5}
                    rx={4}
                    ry={5}
                    fill={SKY}
                    data-mouth="o"
                />
            );
        case 'open':
            return (
                <path
                    d={`M${CX - 8} ${EYE_Y + 11} Q${CX} ${EYE_Y + 21.5} ${CX + 8} ${EYE_Y + 11} Z`}
                    fill={SKY}
                    data-mouth="open"
                />
            );
        default:
            return (
                <Stroke
                    d={`M${CX - 7} ${EYE_Y + 13} Q${CX} ${EYE_Y + 17} ${CX + 7} ${EYE_Y + 13}`}
                />
            );
    }
}

function Detail({ kind }: Readonly<{ kind: DetailKind }>) {
    switch (kind) {
        case 'sunrise':
            return (
                <Stroke
                    d={`M${CX - 9} 72.5 a9 9 0 0 1 18 0`}
                    width={2.2}
                    color={CREAM}
                />
            );
        case 'rain':
            return (
                <Stroke
                    d={`M${CX - 10} 70.5 v3 M${CX} 70 v4 M${CX + 10} 70.5 v3`}
                    width={2}
                    color={CREAM}
                />
            );
        case 'splitPanel':
            return (
                <rect
                    x={CX}
                    y={75}
                    width={31}
                    height={7}
                    fill={CREAM}
                    opacity={0.34}
                />
            );
        case 'speedStripe':
            return (
                <Stroke
                    d={`M${CX - 18} 87 h8 M${CX + 10} 87 h8`}
                    width={2}
                    color={CREAM}
                />
            );
        case 'lugs':
            return (
                <Stroke
                    d={`M${CX - 18} 90 v2 M${CX - 14} 90.5 v2 M${CX - 10} 90 v2 M${CX + 10} 90 v2 M${CX + 14} 90.5 v2 M${CX + 18} 90 v2`}
                    width={1.6}
                    color={INK}
                />
            );
        case 'medalStar':
            return <circle cx={CX} cy={85} r={2.6} fill={SKY} opacity={0.55} />;
        case 'medalRing':
            return (
                <circle
                    cx={CX}
                    cy={85}
                    r={3.4}
                    fill="none"
                    stroke={SKY}
                    strokeWidth={1.3}
                    opacity={0.5}
                />
            );
        default:
            return <circle cx={CX} cy={26} r={2.4} fill={CREAM} />;
    }
}

// ── Slot art ─────────────────────────────────────────────────────────

function Headband({ item }: Readonly<{ item: ItemSpec }>) {
    return (
        <>
            <Band y={23} height={6} fill={item.color} />
            {item.detail !== undefined && <Detail kind={item.detail} />}
        </>
    );
}

function Shirt({ item }: Readonly<{ item: ItemSpec }>) {
    return (
        <>
            <Band y={69} height={6} fill={item.color} />
            <path
                d={`M${CX - 4.5} 69 L${CX} 73 L${CX + 4.5} 69 Z`}
                fill={CREAM}
            />
            {item.detail !== undefined && <Detail kind={item.detail} />}
        </>
    );
}

function Shorts({ item }: Readonly<{ item: ItemSpec }>) {
    return (
        <>
            <Band y={75} height={7} fill={item.color} />
            <path
                d={`M${CX} 75 V82`}
                fill="none"
                stroke={CREAM}
                strokeWidth={1.8}
            />
            {item.detail !== undefined && <Detail kind={item.detail} />}
        </>
    );
}

function Shoes({ item }: Readonly<{ item: ItemSpec }>) {
    return (
        <>
            <ellipse cx={CX - 14} cy={87} rx={8.5} ry={5} fill={item.color} />
            <ellipse cx={CX + 14} cy={87} rx={8.5} ry={5} fill={item.color} />
            {item.detail !== undefined && <Detail kind={item.detail} />}
        </>
    );
}

function Medal({ item }: Readonly<{ item: ItemSpec }>) {
    return (
        <g data-slot="medal">
            <Stroke
                d={`M${CX - 7} 69 L${CX} 77 L${CX + 7} 69`}
                width={3}
                color={LACE}
            />
            <circle
                cx={CX}
                cy={85}
                r={6}
                fill={item.color}
                stroke={GOLD_INK}
                strokeWidth={1.6}
            />
            {item.detail !== undefined && <Detail kind={item.detail} />}
        </g>
    );
}

function Aura({ color, dash }: Readonly<{ color: string; dash: string }>) {
    return (
        <circle
            data-slot="aura"
            cx={CX}
            cy={CY}
            r={AURA_R}
            fill="none"
            stroke={color}
            strokeWidth={2.4}
            strokeDasharray={dash}
            strokeLinecap="round"
            opacity={0.85}
        />
    );
}

function SeasonCoverage({ phase }: Readonly<{ phase: SeasonPhase }>) {
    const config = SEASON_COVERAGE[phase];
    return (
        <>
            {config.angles.map((angle, i) => (
                <ellipse
                    key={angle}
                    cx={CX}
                    cy={CY}
                    rx={BODY_R}
                    ry={11 + i * 3}
                    fill="none"
                    stroke={SEASON_COLORS[i % SEASON_COLORS.length]}
                    strokeWidth={config.width}
                    opacity={config.opacity}
                    transform={`rotate(${angle} ${CX} ${CY})`}
                />
            ))}
            {config.shine === true && (
                <ellipse
                    data-season="shine"
                    cx={CX - 8}
                    cy={CY - 12}
                    rx={14}
                    ry={9}
                    fill="#fffaf0"
                    opacity={0.45}
                    transform={`rotate(-24 ${CX - 8} ${CY - 12})`}
                />
            )}
        </>
    );
}

// ── Helpers ──────────────────────────────────────────────────────────

function resolveAuraKey(equipped: TemariEquipped | null): string | null {
    if (!equipped?.aura) return null;
    if (typeof equipped.aura === 'string') return equipped.aura;
    return 'warmup';
}

function itemFor(
    table: Record<string, ItemSpec>,
    key: string | null | undefined,
    fallback: string,
): ItemSpec | null {
    if (key === null || key === undefined) return null;
    return table[key] ?? table[fallback];
}

// ── Main component ───────────────────────────────────────────────────

function TemariProto({
    pose = 'proud',
    size = 140,
    tone = 'cream',
    equipped = null,
    animate = false,
    dropShadow = true,
    seasonPhase,
    className,
}: Readonly<TemariProtoProps>) {
    const aspectHeight = (size * VIEW_H) / VIEW_W;

    const expression = POSE_TO_EXPRESSION[pose];
    const spec = EXPRESSION_SPEC[expression];
    const halo = HALO[spec.halo];
    const [browOuter, browInner] = spec.brow;
    const [browROuter, browRInner] = spec.browR ?? spec.brow;

    const headband = itemFor(HEADBAND_ITEMS, equipped?.headband, 'uncommon');
    const shirt = itemFor(SHIRT_ITEMS, equipped?.shirt, 'beginner');
    const shorts = itemFor(SHORTS_ITEMS, equipped?.shorts, 'lightweight');
    const shoes = itemFor(SHOES_ITEMS, equipped?.shoes, 'basic');
    const medal =
        !equipped?.medal || equipped.medal === 'none'
            ? null
            : itemFor(MEDAL_ITEMS, equipped.medal, 'first');

    const auraKey = resolveAuraKey(equipped);
    const aura =
        auraKey === null ? null : (AURA_ITEMS[auraKey] ?? AURA_ITEMS.warmup);

    // Several instances render on one page (the accessory catalogue grid), so
    // the clip needs a per-instance id even though the geometry is identical.
    const clipId = `temari-body-clip-${useId()}`;

    let rootAnim: CSSProperties['animation'] = 'none';
    if (animate !== false) {
        rootAnim = typeof animate === 'string' ? animate : POSE_ANIM[pose];
    }

    const character = (
        <g transform={PLACE_TRANSFORM}>
            {aura !== null && <Aura color={aura.color} dash={aura.dash} />}
            <circle
                data-part="halo"
                cx={CX}
                cy={CY}
                r={HALO_R}
                fill="none"
                stroke={halo.color}
                strokeWidth={halo.width}
            />
            {shoes !== null && <Shoes item={shoes} />}
            <circle
                data-part="body"
                cx={CX}
                cy={CY}
                r={BODY_R}
                fill={CREAM}
                stroke={tone === 'sky' ? CREAM : SKY}
                strokeWidth={4.5}
            />
            <g clipPath={`url(#${clipId})`}>
                {seasonPhase !== undefined && (
                    <SeasonCoverage phase={seasonPhase} />
                )}
                {headband !== null && <Headband item={headband} />}
                {shirt !== null && <Shirt item={shirt} />}
                {shorts !== null && <Shorts item={shorts} />}
            </g>
            {medal !== null && <Medal item={medal} />}
            <Brow x={EYE_L} outerY={browOuter} innerY={browInner} side="l" />
            <Brow x={EYE_R} outerY={browROuter} innerY={browRInner} side="r" />
            <Eyes shape={spec.eyes} />
            <Mouth shape={spec.mouth} />
        </g>
    );

    return (
        <div
            className={cn('temari-root', className)}
            style={{ animation: rootAnim, width: size, height: aspectHeight }}
            data-pose={pose}
            data-expression={expression}
            data-tone={tone}
        >
            <svg
                viewBox={`0 ${VIEW_Y} ${VIEW_W} ${VIEW_H}`}
                width={size}
                height={aspectHeight}
                style={{ display: 'block', overflow: 'visible' }}
                aria-hidden
            >
                <defs>
                    <clipPath id={clipId}>
                        <circle cx={CX} cy={CY} r={CLIP_R} />
                    </clipPath>
                    {dropShadow && (
                        <filter
                            id="temari-shadow"
                            x="-20%"
                            y="-10%"
                            width="140%"
                            height="140%"
                        >
                            <feDropShadow
                                dx="0"
                                dy="3"
                                stdDeviation="3"
                                floodColor="#3b2f1f"
                                floodOpacity="0.15"
                            />
                        </filter>
                    )}
                </defs>
                {dropShadow ? (
                    <g filter="url(#temari-shadow)">{character}</g>
                ) : (
                    character
                )}
            </svg>
        </div>
    );
}

/**
 * Field-level comparison so a parent that re-renders with a fresh inline
 * `equipped={{...}}` object doesn't force this SVG tree to rebuild.
 */
function equippedEqual(
    a: TemariEquipped | null,
    b: TemariEquipped | null,
): boolean {
    if (a === b) {
        return true;
    }
    if (a === null || b === null) {
        return false;
    }
    return (
        a.headband === b.headband &&
        a.medal === b.medal &&
        a.shirt === b.shirt &&
        a.shorts === b.shorts &&
        a.shoes === b.shoes &&
        a.aura === b.aura
    );
}

function propsEqual(
    a: Readonly<TemariProtoProps>,
    b: Readonly<TemariProtoProps>,
): boolean {
    return (
        a.pose === b.pose &&
        a.size === b.size &&
        a.tone === b.tone &&
        a.animate === b.animate &&
        a.dropShadow === b.dropShadow &&
        a.seasonPhase === b.seasonPhase &&
        a.className === b.className &&
        equippedEqual(a.equipped ?? null, b.equipped ?? null)
    );
}

export default memo(TemariProto, propsEqual);
