import type { ComponentType, SVGProps } from 'react';

import {
    Activity,
    AlertCircle,
    ArchiveRestore,
    ArrowLeft,
    ArrowRight,
    ArrowUpDown,
    Bandage,
    BadgeCheck,
    Bed,
    Bell,
    BellOff,
    BellRing,
    Bot,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    ChartBar,
    ChartLine,
    Check,
    CircleCheck,
    CircleHelp,
    CirclePlay,
    CircleUser,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ClockAlert,
    Clock,
    CloudAlert,
    CloudCheck,
    CloudOff,
    Copy,
    Crown,
    DatabaseX,
    DollarSign,
    Download,
    EyeOff,
    Feather,
    FileText,
    FilterX,
    Flag,
    Flame,
    Footprints,
    Frown,
    Gift,
    Hash,
    HeartPulse,
    History,
    Info,
    Layers,
    Lightbulb,
    LoaderCircle,
    Lock,
    LogOut,
    MapPin,
    Medal,
    MessageCircle,
    MessageSquareQuote,
    Monitor,
    Moon,
    Mountain,
    Navigation,
    Palette,
    Pencil,
    Pin,
    RefreshCw,
    RefreshCwOff,
    Route,
    RotateCcw,
    Sailboat,
    Save,
    Scale,
    ScanSearch,
    Search,
    Send,
    Server,
    Settings,
    Shapes,
    Share2,
    Shirt,
    SlidersHorizontal,
    Sparkle,
    Sparkles,
    Sprout,
    Star,
    Sun,
    Sunrise,
    Table,
    Target,
    Timer,
    TrendingUp,
    Trophy,
    Undo2,
    Unlink,
    UnfoldHorizontal,
    Users,
    UserX,
    Wind,
    X,
    Zap,
} from 'lucide-react';

/**
 * Every mdi:* key the app renders anywhere (JSX literals, nav/settings/link
 * config arrays, and the backend-sourced UnlockFlash.icon string from
 * config/temari_unlocks.php), mapped to its closest lucide-react icon. The
 * "mdi:" prefix survives the swap as an opaque lookup key only — nothing here
 * still talks to @iconify/react or fetches from api.iconify.design.
 */
const ICON_MAP: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
    'mdi:account-multiple': Users,
    'mdi:account-outline': CircleUser,
    'mdi:account-remove-outline': UserX,
    'mdi:alert-circle-outline': AlertCircle,
    'mdi:arrow-expand-horizontal': UnfoldHorizontal,
    'mdi:arrow-left': ArrowLeft,
    'mdi:arrow-right': ArrowRight,
    'mdi:auto-awesome': Sparkles,
    'mdi:backup-restore': ArchiveRestore,
    'mdi:bandage': Bandage,
    'mdi:bed': Bed,
    'mdi:bell-cog-outline': Bell,
    'mdi:bell-off-outline': BellOff,
    'mdi:bell-outline': Bell,
    'mdi:bell-ring-outline': BellRing,
    'mdi:blur': Sparkles,
    'mdi:calculator-variant-outline': Calculator,
    'mdi:calendar-blank-outline': Calendar,
    'mdi:calendar-check-outline': CalendarCheck,
    'mdi:calendar-week': CalendarDays,
    'mdi:cards-outline': Layers,
    'mdi:cellphone-message': MessageCircle,
    'mdi:chart-bar': ChartBar,
    'mdi:chart-line': ChartLine,
    'mdi:chat-outline': MessageCircle,
    'mdi:check': Check,
    'mdi:check-circle': CircleCheck,
    'mdi:check-circle-outline': CircleCheck,
    'mdi:chevron-down': ChevronDown,
    'mdi:chevron-left': ChevronLeft,
    'mdi:chevron-right': ChevronRight,
    'mdi:chevron-up': ChevronUp,
    'mdi:clock-alert-outline': ClockAlert,
    'mdi:clock-outline': Clock,
    'mdi:close': X,
    'mdi:cloud-alert-outline': CloudAlert,
    'mdi:cloud-check-variant-outline': CloudCheck,
    'mdi:cloud-off-outline': CloudOff,
    'mdi:cog-outline': Settings,
    'mdi:comment-quote-outline': MessageSquareQuote,
    'mdi:content-copy': Copy,
    'mdi:content-save-outline': Save,
    'mdi:counter': Hash,
    'mdi:crown': Crown,
    'mdi:currency-usd': DollarSign,
    'mdi:database-off': DatabaseX,
    'mdi:emoticon-sad-outline': Frown,
    'mdi:eye-off-outline': EyeOff,
    'mdi:feather': Feather,
    'mdi:file-document-outline': FileText,
    'mdi:filter-remove-outline': FilterX,
    'mdi:filter-variant': SlidersHorizontal,
    'mdi:fire': Flame,
    'mdi:flag-checkered': Flag,
    'mdi:gift': Gift,
    'mdi:hanger': Shirt,
    'mdi:heart-pulse': HeartPulse,
    'mdi:help-circle-outline': CircleHelp,
    'mdi:help-rhombus-outline': CircleHelp,
    'mdi:history': History,
    'mdi:information-outline': Info,
    'mdi:layers-outline': Layers,
    'mdi:lightbulb-on-outline': Lightbulb,
    'mdi:lightning-bolt': Zap,
    'mdi:lingerie': Shirt,
    'mdi:link-off': Unlink,
    'mdi:loading': LoaderCircle,
    'mdi:lock-outline': Lock,
    'mdi:logout': LogOut,
    'mdi:magnify': Search,
    'mdi:magnify-scan': ScanSearch,
    'mdi:map-marker-distance': Route,
    'mdi:map-marker-outline': MapPin,
    'mdi:medal': Medal,
    'mdi:medal-outline': Medal,
    'mdi:monitor': Monitor,
    'mdi:navigation': Navigation,
    'mdi:palette-swatch-outline': Palette,
    'mdi:pencil-outline': Pencil,
    'mdi:pin': Pin,
    'mdi:play-circle-outline': CirclePlay,
    'mdi:progress-clock': LoaderCircle,
    'mdi:progress-download': Download,
    'mdi:pulse': Activity,
    'mdi:refresh': RefreshCw,
    'mdi:restore': RotateCcw,
    'mdi:robot-outline': Bot,
    'mdi:run': Footprints,
    'mdi:sail-boat': Sailboat,
    'mdi:scale-balance': Scale,
    'mdi:seal-variant': BadgeCheck,
    'mdi:send': Send,
    'mdi:send-outline': Send,
    'mdi:server': Server,
    'mdi:shape': Shapes,
    'mdi:share-variant': Share2,
    'mdi:shoe-print': Footprints,
    'mdi:shoe-sneaker': Footprints,
    'mdi:sleep': Moon,
    'mdi:sparkle-outline': Sparkle,
    'mdi:sprout': Sprout,
    'mdi:star': Star,
    'mdi:swap-vertical-bold': ArrowUpDown,
    'mdi:sync': RefreshCw,
    'mdi:sync-off': RefreshCwOff,
    'mdi:table': Table,
    'mdi:target': Target,
    'mdi:terrain': Mountain,
    'mdi:timer-outline': Timer,
    'mdi:trending-up': TrendingUp,
    'mdi:trophy': Trophy,
    'mdi:trophy-outline': Trophy,
    'mdi:tshirt-crew': Shirt,
    'mdi:tshirt-crew-outline': Shirt,
    'mdi:tune-variant': SlidersHorizontal,
    'mdi:undo-variant': Undo2,
    'mdi:weather-night': Moon,
    'mdi:weather-sunset-up': Sunrise,
    'mdi:weather-windy': Wind,
    'mdi:white-balance-sunny': Sun,
};

/**
 * Brand marks. Never restyled or re-drawn in lucide's stroke style — Strava
 * can revoke API access for brand-guideline violations, and Telegram's glyph
 * is a fixed, recognisable mark. Kept as the exact paths iconBundle.ts shipped.
 */
const BRAND_ICONS: Record<string, string> = {
    'mdi:strava':
        'M14.92 17.16l1.83-3.63h2.7l-4.51 8.97l-4.57-8.97h2.7l1.85 3.63m-4.29-8.5l-2.45 4.89H4.55L10.61 1.5l6.13 12.05h-3.63l-2.48-4.89z',
    'mdi:telegram':
        'M9.78 18.65l.28-4.23l7.68-6.92c.34-.31-.07-.46-.52-.19L7.74 13.3L3.64 12c-.88-.25-.89-.86.2-1.3l15.97-6.16c.73-.33 1.43.18 1.15 1.3l-2.72 12.81c-.19.91-.74 1.13-1.5.71L12.6 16.3l-1.99 1.93c-.23.23-.42.42-.83.42z',
};

export function Icon({
    icon,
    width,
    height,
    className,
    ...rest
}: { icon: string } & Omit<SVGProps<SVGSVGElement>, 'icon'>) {
    const size = width ?? height ?? 24;
    const brandPath = BRAND_ICONS[icon];
    if (brandPath !== undefined) {
        return (
            <svg
                width={size}
                height={size}
                viewBox="0 0 24 24"
                className={className}
                {...rest}
            >
                <path fill="currentColor" d={brandPath} />
            </svg>
        );
    }

    const Component = ICON_MAP[icon];
    if (!Component) {
        return null;
    }

    return (
        <Component width={size} height={size} className={className} {...rest} />
    );
}
