// AUTO-GENERATED by `php artisan typescript:enums`. Do not edit by hand.
// Regenerate after changing any backed PHP enum; CI fails if stale.

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export const RARITY_VALUES = ['common', 'uncommon', 'rare', 'epic', 'legendary'] as const;

export type PrCategory = '1km' | '5km' | '10km' | '15km' | 'half_marathon' | 'marathon' | 'best_5min' | 'best_10min' | 'best_20min' | 'best_30min' | 'best_60min';
export const PR_CATEGORY_VALUES = ['1km', '5km', '10km', '15km', 'half_marathon', 'marathon', 'best_5min', 'best_10min', 'best_20min', 'best_30min', 'best_60min'] as const;

export type AnalysisStatus = 'pending' | 'queued' | 'processing' | 'done' | 'failed';
export const ANALYSIS_STATUS_VALUES = ['pending', 'queued', 'processing', 'done', 'failed'] as const;

export type AnalysisType = 'briefing_mascot_voice' | 'post_run_speech' | 'run_insight' | 'weekly_recap' | 'card_flavor' | 'profile_voice' | 'monthly_recap' | 'trend_read' | 'plan_day_voice' | 'plan_clamp_voice' | 'plan_week_voice' | 'plan_season_voice';
export const ANALYSIS_TYPE_VALUES = ['briefing_mascot_voice', 'post_run_speech', 'run_insight', 'weekly_recap', 'card_flavor', 'profile_voice', 'monthly_recap', 'trend_read', 'plan_day_voice', 'plan_clamp_voice', 'plan_week_voice', 'plan_season_voice'] as const;

export type NotificationKind = 'post_run' | 'weekly_recap' | 'monthly_recap' | 'streak_reminder' | 'plan_clamp' | 'strava_disconnected' | 'race_tomorrow' | 'test';
export const NOTIFICATION_KIND_VALUES = ['post_run', 'weekly_recap', 'monthly_recap', 'streak_reminder', 'plan_clamp', 'strava_disconnected', 'race_tomorrow', 'test'] as const;

export type PlannedSessionStatus = 'planned' | 'done' | 'partial' | 'missed' | 'overreached' | 'skip';
export const PLANNED_SESSION_STATUS_VALUES = ['planned', 'done', 'partial', 'missed', 'overreached', 'skip'] as const;

export type ExperienceLevel = 'new_to_running' | 'returning' | 'experienced';
export const EXPERIENCE_LEVEL_VALUES = ['new_to_running', 'returning', 'experienced'] as const;

export type GoalType = 'consistent' | 'race' | 'base' | 'return';
export const GOAL_TYPE_VALUES = ['consistent', 'race', 'base', 'return'] as const;

export type FeedbackSubject = 'plan_day' | 'narration';
export const FEEDBACK_SUBJECT_VALUES = ['plan_day', 'narration'] as const;

export type FeedbackReason = 'facts_wrong' | 'tone_off' | 'too_long' | 'ignores_my_plan' | 'wrong_day' | 'too_hard' | 'too_easy' | 'wrong_pace';
export const FEEDBACK_REASON_VALUES = ['facts_wrong', 'tone_off', 'too_long', 'ignores_my_plan', 'wrong_day', 'too_hard', 'too_easy', 'wrong_pace'] as const;

export type AnchorKind = 'split' | 'zone' | 'metric' | 'session';
export const ANCHOR_KIND_VALUES = ['split', 'zone', 'metric', 'session'] as const;
