#!/usr/bin/env bash
set -euo pipefail

#   ./scripts/worktree-setup.sh <slot: 1|2|3>
#
# Run once per worktree, right after `git worktree add` / EnterWorktree. See
# the "temari" skill's "Parallel worktrees" section.

usage() {
  echo "Usage: $0 <slot: 1|2|3>" >&2
  exit 1
}

[ $# -eq 1 ] || usage

case "$1" in
  1) APP_PORT=7011; VITE_PORT=7012 ;;
  2) APP_PORT=7021; VITE_PORT=7022 ;;
  3) APP_PORT=7031; VITE_PORT=7032 ;;
  *) usage ;;
esac

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ "$(git rev-parse --git-common-dir)" = ".git" ]; then
  echo "worktree-setup: this is the main checkout, not a linked worktree — refusing to touch its .env" >&2
  exit 1
fi

[ -f .env ] || cp .env.example .env

set_env_var() {
  if grep -qE "^${1}=" .env; then
    sed -i.bak -E "s|^${1}=.*|${1}=${2}|" .env && rm -f .env.bak
  else
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}

set_env_var APP_PORT "$APP_PORT"
set_env_var VITE_PORT "$VITE_PORT"
set_env_var APP_URL "http://localhost:${APP_PORT}"

# A worktree's .git is a file pointing at <main repo>/.git/worktrees/<name> — a
# host path outside this checkout's bind mount, so git can't resolve the repo
# from inside the container and Pest's TIA engine panics instead of degrading.
# Mount the shared git dir and point GIT_DIR at this worktree's slot. Compose
# auto-loads this override; the main checkout has none and is unaffected.
GIT_COMMON_DIR="$(git rev-parse --path-format=absolute --git-common-dir)"
GIT_WORKTREE_DIR="$(git rev-parse --path-format=absolute --git-dir)"

cat > compose.override.yaml <<EOF
# Generated by scripts/worktree-setup.sh — not tracked, safe to delete.
services:
    app:
        volumes:
            - '${GIT_COMMON_DIR}:/gitcommon'
        environment:
            GIT_DIR: /gitcommon${GIT_WORKTREE_DIR#"$GIT_COMMON_DIR"}
            GIT_WORK_TREE: /var/www/html
EOF

docker compose up -d
docker compose exec -u root app chown -R www-data:www-data node_modules /var/cache/composer /var/cache/npm

# vendor/ is empty on a fresh worktree, so ./vendor/bin/sail doesn't exist yet —
# everything below uses the plain `docker compose exec` form. Each step is
# guarded or idempotent, so re-running the script after a transient failure
# (the known cold-install bind-mount race) is safe.
app() { docker compose exec -T app "$@"; }

[ -f vendor/autoload.php ] || app composer install

# Only when unset: re-running key:generate would rotate APP_KEY and invalidate
# every existing session in this worktree.
grep -qE '^APP_KEY=.+' .env || app php artisan key:generate

app php artisan migrate --force

# The analytics schema is a SECOND connection with its own migration path, so a
# plain `migrate` does not touch it. Skipping this leaves strava_sync_logs and
# ai_token_usages missing, which 500s /pulse and /ai-usage — a gap every
# worktree hit, because it only ever lived in this script's printed next-steps.
# The schema itself is created on a fresh volume by docker/mysql/init.
app php artisan migrate --database=analytics --path=database/migrations/analytics --force

cat <<EOF
worktree-setup: slot $1 configured — APP_PORT=$APP_PORT, VITE_PORT=$VITE_PORT.
Stack is up, PHP deps installed, both the app and analytics schemas migrated.
Composer/npm caches are shared across worktrees, so installs after the first
one should be faster.

The PHP suites are ready now (they use their own self-initializing
mysql_test/redis_test). To also load pages in a browser:
  ./vendor/bin/sail npm ci
  ./vendor/bin/sail npm run dev            # or \`npm run build\` for a one-shot build
EOF
